// LOCALHOST
###
POST http://localhost:3000/contacts/create-contact
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "favoriteColor": "blue",
  "birthday": "1990-01-01"
}
###
PUT http://localhost:3000/contacts/6795ba4a0c53f9535f3ccde0
Content-Type: application/json

{
    "favoriteColor": "green"
}
###
DELETE http://localhost:3000/contacts/6795ba4a0c53f9535f3ccde0

// PROD Deploy
###
POST https://cse-341-rgdc.onrender.com/contacts/create-contact
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "favoriteColor": "Blue",
  "birthday": "1990-01-01"
}
###
PUT https://cse-341-rgdc.onrender.com/contacts/6795ba739a21f155e3f3cdd0
Content-Type: application/json

{
    "favoriteColor": "Green"
}
###
DELETE https://cse-341-rgdc.onrender.com/contacts/6795ba739a21f155e3f3cdd0